# Generated by Django 2.0.5 on 2020-06-16 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0003_auto_20200606_1918'),
    ]

    operations = [
        migrations.CreateModel(
            name='check_date',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('work_title', models.CharField(max_length=34)),
                ('doctor_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='doctor.Doctor')),
            ],
        ),
    ]
