# Generated by Django 2.0.5 on 2020-06-18 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0004_check_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='email_id',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
