# Generated by Django 2.0.5 on 2020-06-19 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_auto_20200606_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
